import { CommunityList } from './types';

export const COMMUNITY_LISTS: CommunityList[] = [
  {
    id: 'ai-tools',
    title: 'Top AI & LLM Tools',
    description: 'Essential artificial intelligence models, assistants, and generative AI platforms.',
    category: 'AI',
    badge: 'Popular',
    icon: '🤖',
    links: [
      { name: 'ChatGPT', url: 'https://chatgpt.com', description: 'OpenAI conversational model' },
      { name: 'Claude', url: 'https://claude.ai', description: 'Anthropic reasoning assistant' },
      { name: 'Perplexity', url: 'https://perplexity.ai', description: 'AI conversational search' },
      { name: 'v0.dev', url: 'https://v0.dev', description: 'Generative UI by Vercel' },
      { name: 'Hugging Face', url: 'https://huggingface.co', description: 'Open-source AI community' },
      { name: 'Midjourney', url: 'https://midjourney.com', description: 'Generative AI art platform' },
    ],
  },
  {
    id: 'web-dev',
    title: 'Modern Web Dev Stack',
    description: 'Core tools, frameworks, and deployment engines for modern full-stack engineers.',
    category: 'Dev',
    badge: 'Featured',
    icon: '🛠️',
    links: [
      { name: 'GitHub', url: 'https://github.com', description: 'Version control & collaboration' },
      { name: 'Vercel', url: 'https://vercel.com', description: 'Frontend cloud deployment' },
      { name: 'Next.js', url: 'https://nextjs.org', description: 'React framework for the web' },
      { name: 'Tailwind CSS', url: 'https://tailwindcss.com', description: 'Utility-first CSS' },
      { name: 'TypeScript', url: 'https://www.typescriptlang.org', description: 'Typed JavaScript at scale' },
      { name: 'Supabase', url: 'https://supabase.com', description: 'Open source Firebase alternative' },
    ],
  },
  {
    id: 'productivity',
    title: 'Workspace & Productivity',
    description: 'High-leverage tools for project tracking, note-taking, and async team work.',
    category: 'Productivity',
    badge: 'Essential',
    icon: '⚡',
    links: [
      { name: 'Notion', url: 'https://notion.so', description: 'Connected workspace & docs' },
      { name: 'Linear', url: 'https://linear.app', description: 'Purpose-built issue tracking' },
      { name: 'Figma', url: 'https://figma.com', description: 'Collaborative interface design' },
      { name: 'Raycast', url: 'https://raycast.com', description: 'Supercharged Mac/Win launcher' },
      { name: 'Obsidian', url: 'https://obsidian.md', description: 'Second brain markdown notes' },
      { name: 'Slack', url: 'https://slack.com', description: 'Team messaging platform' },
    ],
  },
  {
    id: 'tech-news',
    title: 'Tech & Hacker News Hub',
    description: 'Real-time engineering discussions, product launches, and industry breakthroughs.',
    category: 'News',
    icon: '📰',
    links: [
      { name: 'Hacker News', url: 'https://news.ycombinator.com', description: 'Y Combinator community' },
      { name: 'Product Hunt', url: 'https://producthunt.com', description: 'Daily new product launches' },
      { name: 'DEV Community', url: 'https://dev.to', description: 'Constructive dev articles' },
      { name: 'Lobsters', url: 'https://lobste.rs', description: 'Computing-focused news' },
      { name: 'Hashnode', url: 'https://hashnode.com', description: 'Developer blogging platform' },
      { name: 'TechCrunch', url: 'https://techcrunch.com', description: 'Startup & technology news' },
    ],
  },
  {
    id: 'design-ui',
    title: 'Design & UI Inspiration',
    description: 'Curated galleries of world-class web designs, mobile apps, and micro-interactions.',
    category: 'Design',
    badge: 'Curated',
    icon: '🎨',
    links: [
      { name: 'Dribbble', url: 'https://dribbble.com', description: 'Design portfolio showcase' },
      { name: 'Mobbin', url: 'https://mobbin.com', description: 'Real-world app UI library' },
      { name: 'Godly', url: 'https://godly.website', description: 'Curated modern web designs' },
      { name: 'Layers', url: 'https://layers.to', description: 'Creative community for designers' },
      { name: 'Refero', url: 'https://refero.design', description: 'Curated design patterns' },
      { name: 'Behance', url: 'https://behance.net', description: 'Creative work showcase' },
    ],
  },
  {
    id: 'devops-cloud',
    title: 'DevOps & Cloud Infrastructure',
    description: 'Cloud hosting, containerization, serverless databases, and edge networks.',
    category: 'Dev',
    icon: '🛡️',
    links: [
      { name: 'Cloudflare', url: 'https://dash.cloudflare.com', description: 'Global edge network & DNS' },
      { name: 'Docker Hub', url: 'https://hub.docker.com', description: 'Container repository' },
      { name: 'AWS Console', url: 'https://aws.amazon.com/console', description: 'Amazon Web Services' },
      { name: 'Railway', url: 'https://railway.app', description: 'Instant app deployment' },
      { name: 'Fly.io', url: 'https://fly.io', description: 'Deploy servers near users' },
      { name: 'Datadog', url: 'https://datadoghq.com', description: 'Cloud observability platform' },
    ],
  },
];
